server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:postgresql://aviation.chmribipukal.us-west-2.rds.amazonaws.com:5432/aviationdb?user=root&password=aviation123&ssl=false
    username: root
    password: aviation123
    dbcp:
      max-active: 5
    tomcat:
      max-active: 5
 
---
server:
  context-path: /
  max-http-header-size: 2012333
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  http:
    multipart:
      max-request-size: 10Mb
---
spring:
  datasource:
    url:
      jdbc:postgresql://aviation.chmribipukal.us-west-2.rds.amazonaws.com:5432/aviationdb?user=root&password=aviation123&ssl=false
